# Generated by Django 6.1.1 on 2026-09-10 19:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ročník',
                'verbose_name_plural': 'ročníky',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'typ materiálu',
                'verbose_name_plural': 'typy materiálů',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'štítek',
                'verbose_name_plural': 'štítky',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'téma',
                'verbose_name_plural': 'témata',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('pdf_file', models.FileField(upload_to='materials/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('status', models.CharField(choices=[('draft', 'Koncept'), ('published', 'Publikováno'), ('archived', 'Archivováno')], default='draft', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grades', models.ManyToManyField(related_name='materials', to='materials.grade')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='materials.materialtype')),
                ('tags', models.ManyToManyField(blank=True, related_name='materials', to='materials.tag')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='materials.topic')),
            ],
            options={
                'verbose_name': 'materiál',
                'verbose_name_plural': 'materiály',
                'ordering': ['topic__order', 'order', 'title'],
            },
        ),
    ]
