# Generated by Django 6.1.1 on 2026-09-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='html_content',
            field=models.TextField(blank=True, help_text='HTML obsah vygenerovaný z LaTeXu.'),
        ),
    ]
