# Generated by Django 6.1.1 on 2026-09-12 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_material_html_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('html_content', models.TextField(blank=True, help_text='HTML obsah kapitoly vygenerovaný z LaTeXu.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='materials.material')),
            ],
            options={
                'verbose_name': 'kapitola materiálu',
                'verbose_name_plural': 'kapitoly materiálů',
                'ordering': ['order', 'title'],
                'constraints': [models.UniqueConstraint(fields=('material', 'slug'), name='unique_material_section_slug')],
            },
        ),
    ]
