# Generated by Django 6.1.1 on 2026-09-12 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_materialsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='source_tex',
            field=models.FileField(blank=True, help_text='Zdrojový LaTeX soubor materiálu.', upload_to='sources/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['tex'])]),
        ),
    ]
