# Generated by Django 6.1.1 on 2026-09-13 15:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_material_source_tex'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='source_material',
            field=models.ForeignKey(blank=True, help_text='Zdrojový materiál, ze kterého byl tento materiál automaticky odvozen.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derived_materials', to='materials.material'),
        ),
        migrations.AlterField(
            model_name='material',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='materials/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
