# Generated by Django 6.1.1 on 2026-09-18 20:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0005_material_source_material_alter_material_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, upload_to='sidequests/pdf/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('source_tex', models.FileField(blank=True, upload_to='sidequests/sources/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['tex'])])),
                ('status', models.CharField(choices=[('draft', 'Koncept'), ('published', 'Publikováno'), ('archived', 'Archivováno')], default='draft', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='sidequests', to='materials.tag')),
            ],
            options={
                'verbose_name': 'bokovka',
                'verbose_name_plural': 'bokovky',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SideQuestSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('html_content', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sidequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='sidequests.sidequest')),
            ],
            options={
                'verbose_name': 'kapitola bokovky',
                'verbose_name_plural': 'kapitoly bokovek',
                'ordering': ['order', 'title'],
                'constraints': [models.UniqueConstraint(fields=('sidequest', 'slug'), name='unique_sidequest_section_slug')],
            },
        ),
    ]
