# Generated by Django 6.1.1 on 2026-09-18 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidequests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidequest',
            name='source_tex',
            field=models.FileField(blank=True, help_text='Zdrojový LaTeX. Webové kapitoly se vyznačují komentářem % MATHERA-SECTION: Název kapitoly.', upload_to='sidequests/sources/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['tex'])]),
        ),
        migrations.AlterField(
            model_name='sidequestsection',
            name='html_content',
            field=models.TextField(blank=True, help_text='HTML obsah kapitoly vygenerovaný z LaTeXu.'),
        ),
    ]
