# Generated by Django 6.1.1 on 2026-09-14 12:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('term', models.CharField(choices=[('spring', 'Jaro'), ('autumn', 'Podzim'), ('other', 'Jiný termín')], default='spring', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('source_pdf', models.FileField(blank=True, help_text='Originální PDF testu, ze kterého se automaticky vytvářejí výřezy zadání.', upload_to='exams/source-pdf/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('source_tex', models.FileField(blank=True, help_text='LaTeX se značkami \\uloha{...}{\\zadani{...}} a řešeními.', upload_to='exams/source-tex/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['tex'])])),
                ('status', models.CharField(choices=[('draft', 'Koncept'), ('published', 'Publikováno'), ('archived', 'Archivováno')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'maturita',
                'verbose_name_plural': 'maturity',
                'ordering': ['-year', 'term', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ExamTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('page_number', models.PositiveSmallIntegerField()),
                ('trim_left_mm', models.DecimalField(decimal_places=3, max_digits=8)),
                ('trim_bottom_mm', models.DecimalField(decimal_places=3, max_digits=8)),
                ('trim_right_mm', models.DecimalField(decimal_places=3, max_digits=8)),
                ('trim_top_mm', models.DecimalField(decimal_places=3, max_digits=8)),
                ('statement_image', models.FileField(blank=True, help_text='Automaticky vygenerovaný výřez zadání z originálního PDF.', upload_to='')),
                ('solution_tex', models.TextField(blank=True, help_text='Zdroj řešení vytažený z hlavního LaTeXového souboru.')),
                ('solution_html', models.TextField(blank=True, help_text='HTML řešení vygenerované z LaTeXu.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='exams.exam')),
            ],
            options={
                'verbose_name': 'maturitní úloha',
                'verbose_name_plural': 'maturitní úlohy',
                'ordering': ['order', 'number'],
                'constraints': [models.UniqueConstraint(fields=('exam', 'number'), name='unique_exam_task_number')],
            },
        ),
    ]
